controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel: ['left_wheel_joint']
    arm_joints_controller:
      type: forward_command_controller/ForwardCommandController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['base_left_wheel_joint']
    right_wheel_names: ['base_right_wheel_joint']

    wheel_separation: 0.45  # Distance between the wheels in meters
    wheel_radius: 0.1      # Radius of the wheels in meters

    odom_frame: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    enable_odom_tf: true
    publish_rate: 50.0

arm_joints_controller:
  ros__parameters:
    joints: ['arm_joint1', 'arm_joint2']
    interface_name: 'position'